name = "website"
pages_build_output_dir = "dist"
compatibility_date = "2026-06-06"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "SESSION"
id = "feb3eec0c7e347eea7b3b8998914a0a5"
